### ISSUE TITLE
`Codemirror plugin crashed: TypeError: tags4 is undefined`

### ISSUE THREAD

**Issue by NashJames** [uiwjs/react-codemirror#401]
So this error appears in the console on every page load when trying to load a language extension on both firefox and chrome (although chrome defines it as `Codemirror plugin crashed: TypeError: tags4 is not iterable`). 

I've tried using `loadLanguage('json')` from @uiw/codemirror-extensions-langs and `json()` from @codemirror/lang-json. No formatting is applied. The code mirror appears to work correctly.

```
@uiw/react-codemirror v4.13.0
@uiw/codemirror-extensions-langs v4.13.0
parcel v2.4.0
@codemirror/lang-json v6.0.1
```
<details>
  <summary>Error screenshot</summary>

![Screenshot 2022-11-10 at 11 56 10](https://user-images.githubusercontent.com/37304960/201086474-fafa63b3-efba-4155-b65a-f37fb60c05d1.png)
</details>

Also, I've written some code to determine language based on file extension like below, but I have to write a huge type for it because `loadLanguage()` doesn't allow strings unless they match a type. You can't use `typeof langNames` because it's formatted with `()[]`. Adding a type to the repo would be very helpful.
```tsx
type languages = "apl" | "asciiArmor" | ...

const path = "example/path.tsx"
const split = path.split(".")
const lang =  split[split.length - 1] as languages

...

extensions={[loadLanguage(lang)]}
```

**Comment by jaywcjlove** [comment]
Can you provide a reproducible example using [codesandbox.io](https://codesandbox.io/embed/react-codemirror-example-codemirror-6-slvju?fontsize=14&hidenavigation=1&theme=dark)?

@NashJames

**Comment by NashJames** [comment]
Just spent an hour trying. Hit one error on the sandbox, and another on github codespaces. No idea what caused either.

![image](https://user-images.githubusercontent.com/37304960/201222818-303d6c4d-f6c0-4f94-9402-3c9f443f5bd3.png)

![image](https://user-images.githubusercontent.com/37304960/201222866-240a0f55-f1a0-40a2-a7cb-1d34f752b32f.png)

**Comment by jaywcjlove** [comment]
@NashJames   I don't have any problems locally but I have problems on [codesandbox example](https://codesandbox.io/s/react-codemirror-uiwjs-react-codemirror-issues-401-ch7hwr?file=/src/App.tsx)


![image](https://user-images.githubusercontent.com/1680273/201274543-2d904a32-3f30-4dc3-9374-f642e942eb62.png)

I don't know how to solve it, if you solved it please share your answer. 

thx!

**Comment by NashJames** [comment]
For the time being, my plan is to use it without language support. If I ever give it another go and figure out the cause, I’ll come back and let you know.

Up to you if you wish to close this. I can always reopen if I do figure it out.

**Comment by miguelski** [comment]
also using parcel and i got the error
![image](https://user-images.githubusercontent.com/72758941/207150993-92b8b907-3fcf-4c18-a60f-a8fe6f40e852.png)

**Comment by NashJames** [comment]
Thanks @miguelski. I'm assuming this is the correct fix but we're not in a position to upgrade parcel due to another bug. So I can't test.

I'll consider this fixed and close the issue and make a note in our project readme.

**Comment by karlhorky** [comment]
What worked for me was manually editing the Yarn lockfile (`yarn.lock`) to remove any entries which had `>1` version numbers that were conflicting (eg. `@lezer/common@1.0.2` and `@lezer/common@1.0.3`) and then re-running `yarn install` to install the latest version.

Often I use [Yarn Resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) or [pnpm Overrides](https://pnpm.io/package_json#pnpmoverrides) to force the versions of transitive dependencies, which avoids this problem when upgrading dependencies. However, like some others in this thread, I have a dependency on older (pre-v1) versions of `@lezer/common` and `@lezer/lr` packages via Parcel 😨 So for these packages, Yarn Resolutions and pnpm Overrides cannot be used, because they will cause incompatibilities with the `@mischnic/json-sourcemap` dependency from Parcel.

So manual upgrades for now until we can either remove the Parcel dependency or upgrade it (currently it's pinned on an old version from a different dependency).
