### ISSUE TITLE
White box in auto completetion instead of dark box in Dracula mode

### ISSUE THREAD

**Issue by NaviTheCoderboi** [uiwjs/react-codemirror#438]
### Describe the issue

When i use auto completetion, the suggestion box should be dark but it's white, pls fix it or tell me a solution pls
![IMG_20221218_185000](https://user-images.githubusercontent.com/102732282/208706146-a224036f-e915-4f51-bbca-78f8cf4a60d6.jpg)

**Comment by jaywcjlove** [comment]
@NaviTheCoderboi 
<img width="345" alt="image" src="https://user-images.githubusercontent.com/1680273/209046373-7639cfff-6958-4183-ae10-9057785af4ee.png">

I'm not sure how your theme is set up.

Are you sure it's a dark theme? rather than a bright theme.

https://github.com/uiwjs/react-codemirror/blob/86c484572bbbec32d64735f975ce0e2a8b51c6cb/core/src/theme/light.ts#L3-L12

**Comment by NaviTheCoderboi** [comment]
@jaywcjlove do i need to specify it dark theme?

**Comment by jaywcjlove** [comment]
@NaviTheCoderboi yes
