### ISSUE TITLE
CodeMirror Merge example has a bug

### ISSUE THREAD

**Issue by BunnyGeorgianIvan** [uiwjs/react-codemirror#530]
There seems to be a bug in the example. 
Whenever a change/render occurs, the editor loses focus and is reset/reinitialized. with the original value.

https://uiwjs.github.io/react-codemirror/#/merge/onchange
https://codesandbox.io/s/wonderful-kate-xr2sd9?file=/src/App.js:303-316

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-codemirror/blob/528759f6f0b47bd0bebdb7c49bfbec63dbd56264/merge/src/Internal.tsx#L98-L116

@BunnyGeorgianIvan This is because I cannot compare whether the extensions have changed, and I am still at a loss.

https://github.com/uiwjs/react-codemirror/blob/528759f6f0b47bd0bebdb7c49bfbec63dbd56264/merge/src/Internal.tsx#L89-L95

**Comment by jaywcjlove** [comment]
<img width="955" alt="image" src="https://github.com/uiwjs/react-codemirror/assets/1680273/a5d5c84d-d4f7-48e3-898b-e02344a15df8">

@BunnyGeorgianIvan If I use `dispatch` to update `extension` it will throw an error. So I used a special method to solve this problem, but it caused a new problem, that is, the editor will be re-rendered.

I think this problem may need to be solved officially by `@codemirror/merge`

https://github.com/uiwjs/react-codemirror/blob/528759f6f0b47bd0bebdb7c49bfbec63dbd56264/merge/src/Internal.tsx#L89-L95

https://github.com/uiwjs/react-codemirror/blob/528759f6f0b47bd0bebdb7c49bfbec63dbd56264/merge/src/Internal.tsx#L77-L82
