### ISSUE TITLE
Syntax highlighter for mermaid language is not working.

### ISSUE THREAD

**Issue by hsingh-ds** [uiwjs/react-codemirror#604]
Here is the code that I am using in React. 
```
<ReactCodeMirror 
        placeholder={"Write your mermaid code here..."}
        style={{width: "100%", resize: "vertical"}} 
        extensions={[langs.mermaid()]} 
        basicSetup={{
          lineNumbers: false,
          foldGutter: false,
          syntaxHighlighting: true,
        }}
```
Syntax highlighting is working for other languages but it is not working for mermaid.

**Comment by jaywcjlove** [comment]
https://stackblitz.com/edit/stackblitz-starters-thwdpq?file=src%2FApp.tsx


I see that the official examples are also invalid. You may want to go here to find the answer. -> https://github.com/inspirnathan/codemirror-lang-mermaid

**Comment by inspirnathan** [comment]
Hello @hsingh-ds and @jaywcjlove,

I am the creator of the `codemirror-lang-mermaid` package. Thank you for using it! I stumbled upon this issue when investigating repo usage. The issue discussed above is related to the version of `@codemirror/language` being used. I am using `^6.9.0` in my `package.json` file. In the StackBlitz environment posted above, it is using a static version of `6.6.0`. If this package is updated to the latest version, the syntax highlighting starts working again. I hope this helps!

**Comment by hsingh-ds** [comment]
@inspirnathan thank you.

**Comment by hsingh-ds** [comment]
@inspirnathan thank you for your help. Now, its working.

**Comment by Glavin001** [comment]
Multiple versions of `@codemirror/language` was the culprit, needed to be upgraded and use `resolutions` in `package.json` to de-duplicate dependencies.

I just wasted **_hours_** fruitlessly debugging the broken syntax highlighting, which worked for `javascript` and not for `html` and `xml` without any errors thrown. Thank you @inspirnathan for your help!

[not urgent] Could someone help understand the root cause of this breaking without any error message? Would it be possible to detect the scenario and throw an error so others like @hsingh-ds and myself don't waste so much time on this hidden gotcha? Thanks!
