### ISSUE TITLE
code highlighting

### ISSUE THREAD

**Issue by pxsty0** [uiwjs/react-codemirror#652]
Hi, how can I highlighting error lines of code in uiw codemirror?
I couldn't find anything detailed about this in your documentation.

**Comment by DErekXx** [comment]
Hi.
I faced a similar issue I guess.
It's not possible to override the error className `cm-lintRange-error`, because it overrides any CSS rules, even if I use the special attribute `markClass` to apply my own styles.

The huge problem the CSS className cm-lintRange-error has a wrong background value that does not appear on the error state `url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAw....") `
That is really confusing for me.

**Comment by pxsty0** [comment]
Can managers look now?

**Comment by pxsty0** [comment]
Can managers look now?

**Comment by pxsty0** [comment]
@jaywcjlove

**Comment by jaywcjlove** [comment]
@pxsty0 https://codemirror.net/examples/lint/
